server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: ${rabbitmq.hostname:localhost}
    port: 5672
    username: guest
    password: guest

# config server actuator
management:
  endpoints:
    web:
      exposure:
        include: busrefresh

---
spring.config.activate.on-profile: native, default  # local 프로필은 동작 안 함

spring:
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/works/meetravel/config # MacOS
#          search-locations: ${search.location:file:///${user.home}/works/meetravel/config} # Windows
  # 로컬에서 작업할 땐 각자의 환경에 맞춰줘야 합니다!

---
spring.config.activate.on-profile: dev

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:meetravel-official/config.git
          default-label: main  # main branch
          ignore-local-ssh-settings: true
          skip-ssl-validation: true
          private-key: |
                        ${GIT_SSH_KEY}
    bus:
      enabled: true # webhook 활성화: /monitor 엔드포인트 호출 가능해진다

---
spring.config.activate.on-profile: prod

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:meetravel-official/config.git
          default-label: main  # main branch
          ignore-local-ssh-settings: true
          private-key: |
                        ${GIT_SSH_KEY}
    bus:
      enabled: true # webhook 활성화: /monitor 엔드포인트 호출 가능해진다
