#kind: StorageClass
#apiVersion: storage.k8s.io/v1
#metadata:
#  name: local-storage
#provisioner: kubernetes.io/no-provisioner
#volumeBindingMode: WaitForFirstConsumer
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: jenkins-pv-volume
#  labels:
#    env: production
#    tier: cicd
#    app: jenkins
#    name: jenkins-pvc
#spec:
#  storageClassName: gp2 # 여기 바꿔봄. 안되면 다시 조정!
#  claimRef:
#    name: jenkins-pv-claim
#    namespace: jenkins
#  capacity:
#    storage: 10Gi
#  accessModes:
#    - ReadWriteOnce
#  local:
#    path: /mnt
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: jenkins
#              operator: In
#              values:
#                - jenkins
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: jenkins-pv-claim
#  namespace: jenkins
#spec:
#  storageClassName: local-storage
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  storageClassName: jenkins-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jenkins-pv
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
