apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    env: production
    tier: database
    app: secret
    name: mysql-secret
type: Opaque
data:
  mysql-password: bXNhcG9ydGFs # msaportal base64 encoded