# kubectl apply -f k8s/environments/jenkins/kaniko/secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: docker-config
  namespace: jenkins
type: Opaque
data: # base64 string - docker meetravel account / ref: https://zerohertz.github.io/jenkins-kaniko/
  config.json: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJhdXRoIjogImJXVmxkSEpoZG1Wc09tMTBiMlptYVdOcFlXd3lOVGd5UUE9PSIKICAgIH0KICB9Cn0K
