apiVersion: v1
kind: Service
metadata:
  name: config
  labels:
    env: production
    tier: backend
    app: config
    name: config-service
spec:
  selector:
    env: production
    tier: backend
    app: config
    name: config-pod
  ports:
    - port: 8888
      targetPort: 8888
