// https://github.com/jenkinsci/kubernetes-plugin
podTemplate(
    name: "jenkins-slave",
    serviceAccount: "jenkins",
    containers: [
        containerTemplate(name: "kaniko", image: "gcr.io/kaniko-project/executor:debug", ttyEnabled: true, command: '/busybox/cat'),
        containerTemplate(name: "kubectl", image: "lachlanevenson/k8s-kubectl:v1.25.4", ttyEnabled: true, command: 'cat')
    ],
    volumes: [
        secretVolume(mountPath: '/kaniko/.docker/', secretName: 'docker-config')
    ]
) {
    node(POD_LABEL) {
        def now = java.time.LocalDateTime.now()
        def projectId = "discovery" // 프로젝트 아이디
        def repoUrl = "git://github.com/meetravel-official/meetravel-backend.git"

        // docker
        def dockerImage = "meetravel/meetravel-backend-${projectId}" // 도커허브 이미지
        def dockerImageTag = "latest" // 도커허브 이미지 태그

        stage("git") {
            checkout scm
        }

        stage("gradle") {
            sh script:"""
                #!/bin/bash
                cd ${projectId}
                ls -al
                ./gradlew clean bootJar
            """
        }

        stage("build image") {
            container("kaniko") {
                sh """
                    /kaniko/executor --context ${repoUrl} \
                                     --context-sub-path ${projectId} \
                                     --dockerfile DockerfileK8s \
                                     --destination ${dockerImage}:${dockerImageTag}
                """
            }
        }

        stage("kubernetes") {
            container("kubectl") {
                sh "kubectl rollout restart deployment ${projectId}-deployment"
                sh "kubectl annotate deployment.apps/${projectId}-deployment kubernetes.io/change-cause='Image updated at ${now} by ${env.BUILD_TAG}.'"
            }
        }
    }
}
