server:
  port: 8002 # random port

spring:
  application:
    name: matching_application_form-service

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    format-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MEETRAVEL_DB_LOCAL_URL}
    username: ${MEETRAVEL_DB_USERNAME}
    password: ${MEETRAVEL_DB_PASSWORD}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true

