name: CI - Build "user-service"

on:
  push:
    branches:
      - main
    paths:
      - user-service/**

jobs:
  build:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    env:
      service-name: user-service
      working-directory: ./user-service

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7
      
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: set credentials in application.yaml
      uses: microsoft/variable-substitution@v1
      with:
        files: ./${{ env.working-directory }}/src/main/resources/application.yaml
      env:
          spring.datasource.url: ${{ secrets.MYSQL_DATASOURCE_URL }}
          spring.datasource.username: ${{ secrets.MYSQL_DATASOURCE_USERNAME }}
          spring.datasource.password: ${{ secrets.MYSQL_DATASOURCE_PASSWORD }}
          jwt.secretKey: ${{ secrets.MEETRAVEL_JWT_SECRET_KEY }}
          oauth.kakao.client_id: ${{ secrets.KAKAO_CLIENT_ID }}
          oauth.kakao.client_secret: ${{ secrets.KAKAO_CLIENT_SECRET }}
          oauth.kakao.redirect_uri: ${{ secrets.KAKAO_REDIRECTED_URI }}
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{ env.working-directory }}
      
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ${{ env.working-directory }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build, tag, and push image to Docker Hub to be deployed for K8S
      id: build-image-k8s
      uses: docker/build-push-action@v6.3.0
      with:
        context: ${{ env.working-directory }}
        file: DockerfileK8s
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/meetravel-backend-${{ env.service-name }}:${{ github.run_number }}, ${{ secrets.DOCKERHUB_USERNAME }}/meetravel-backend-${{ env.service-name }}:latest

    # 아래 내용 변경 필수!
    # - name: Setup Kustomize
    #   uses: imranismail/setup-kustomize@v1

    # - name: Checkout kustomize repository
    #   uses: actions/checkout@v2
    #   with:
    #     repository: $GITHUB_USERNAME/k8s-manifest-repo
    #     ref: main
    #     token: \${{ secrets.ACTION_TOKEN }}
    #     path: k8s-manifest-repo

    # - name: Update Kubernetes resources
    #   run: |
    #     echo \${{ steps.login-ecr.outputs.registry }}
    #     echo \${{ steps.image-info.outputs.ecr_repository }}
    #     echo \${{ steps.image-info.outputs.image_tag }}
    #     cd k8s-manifest-repo/overlays/dev/
    #     kustomize edit set image \${{ steps.login-ecr.outputs.registry}}/\${{ steps.image-info.outputs.ecr_repository }}=\${{ steps.login-ecr.outputs.registry}}/\${{ steps.image-info.outputs.ecr_repository }}:\${{ steps.image-info.outputs.image_tag }}
    #     cat kustomization.yaml

    # - name: Commit files
    #   run: |
    #     cd k8s-manifest-repo
    #     git config --global user.email "github-actions@github.com"
    #     git config --global user.name "github-actions"
    #     git commit -am "Update image tag"
    #     git push -u origin main
